quickfixj:
  client:
    config: classpath:quickfixj-client.cfg
    jmx-enabled: true

server:
  port: 8080

management:
  security:
    enabled: false

endpoints:
  quickfixjclient:
    id: qfjclient
    enabled: true
    sensitive: false